MyWeb_MVC/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using Web.DataAccess.Data;
using Web.DataAccess.Repository.IRepository;
using Web.Models;
using Web.Models.ViewModels;
using Web.Utility;

namespace MyWeb_MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
     
        }
        public IActionResult Index()
        {

            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
          
            return View(objCompanyList);
        }
        //create company
        public IActionResult Upsert(int? id)
        {
            
         
           
            if ((id==null|| id==0))
            {
                //create
               return View(new Company()); 
            }
            else
            {
                //update
                Company companyObj = _unitOfWork.Company.Get(u => u.Id == id);
                return View(companyObj);

            }
        }
        [HttpPost]
        public IActionResult Upsert(Company companyObj, IFormFile? file)
        {
            //Server side Validation

            if (ModelState.IsValid)
            {
               
                
                if(companyObj.Id == 0)
                {
                    _unitOfWork.Company.Add(companyObj);
                }
                else
                {
                    _unitOfWork.Company.Update(companyObj);
                }
               
                _unitOfWork.Save();
                TempData["success"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                
                return View(companyObj);
            }
            
        }
       
        
       
        #region API CALLLs 
        
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> companies = _unitOfWork.Company.GetAll().ToList();

            return Json(new { data = companies });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var companyToBeDeleted = _unitOfWork.Company.Get(u => u.Id == id);
            if (companyToBeDeleted==null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
           
            _unitOfWork.Company.Remove(companyToBeDeleted);
            _unitOfWork.Save(); 
          
            return Json(new { success = true, message = "Deleted successfully" });
        }
        #endregion
    }
}

MyWeb_MVC/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using Web.DataAccess.Data;
using Web.DataAccess.Repository.IRepository;
using Web.Models;
using Web.Models.ViewModels;
using Web.Utility;

namespace MyWeb_MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUnitOfWork _unitOfWork;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {

            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties:"Category").ToList();
          
            return View(objProductList);
        }
        //create product
        public IActionResult Upsert(int? id)
        {
            
         
            ProductVM productVM = new ()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
               Product = new Product()
            };
            if ((id==null|| id==0))
            {
                //create
               return View(productVM); 
            }
            else
            {
                //update
                productVM.Product = _unitOfWork.Product.Get(u => u.Id == id, includeProperties: "ProductImages");
                return View(productVM);

            }
        }
        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, List<IFormFile?> files)
        {
            //Server side Validation

            if (ModelState.IsValid)
            {
                if (productVM.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(productVM.Product);
                }

                _unitOfWork.Save();
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach(IFormFile file in files)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        string productPath =@"images\products\product-"+ productVM.Product.Id;
                        string finalPath = Path.Combine(wwwRootPath, productPath);
                        if(!Directory.Exists(finalPath))
                        {
                            Directory.CreateDirectory(finalPath);
                        }
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        ProductImage productImage = new ProductImage()
                        {
                           ImageUrl = @"\" + productPath + @"\" + fileName,
                            ProductId = productVM.Product.Id
                        };
                        if(productVM.Product.ProductImages == null)
                        {
                            productVM.Product.ProductImages = new List<ProductImage>();
                        }
                        productVM.Product.ProductImages.Add(productImage);
                        
                    }
                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();




                }
                
                TempData["success"] = "Product created/updated successfully";
                return RedirectToAction("Index");
            }
            else
            {
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
                return View(productVM);
            }
            
        }

        public IActionResult DeleteImage(int imageId)
        {
            var imgToBeDeleted = _unitOfWork.ProductImage.Get(u=>u.Id == imageId);
            int productId = imgToBeDeleted.ProductId;   
            if (imgToBeDeleted != null)
            {
                if (!string.IsNullOrEmpty(imgToBeDeleted.ImageUrl)){

                    if (!string.IsNullOrEmpty(imgToBeDeleted.ImageUrl))
                    {
                        //delete the old image
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath,imgToBeDeleted.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                }
                _unitOfWork.ProductImage.Remove(imgToBeDeleted);
                _unitOfWork.Save();
                TempData["success"] = "Image deleted successfully";
            }
            return RedirectToAction(nameof(Upsert), new {id= productId});
        }
       
        
       
        #region API CALLLs 
        
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> products = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return Json(new { data = products });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Product.Get(u => u.Id == id);
            if (productToBeDeleted==null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            string productPath = @"images\products\product-" + id;
            string finalPath = Path.Combine(_webHostEnvironment.WebRootPath, productPath);
            if (Directory.Exists(finalPath))
            {
                string[] filepaths = Directory.GetFiles(finalPath);
                foreach (var filepath in filepaths)
                {
                    System.IO.File.Delete(filepath);
                }
                Directory.Delete(finalPath);
            }

            _unitOfWork.Product.Remove(productToBeDeleted);
            _unitOfWork.Save(); 
          
            return Json(new { success = true, message = "Deleted successfully" });
        }
        #endregion
    }
}

MyWeb_MVC/Areas/Admin/Views/Company/Delete.cshtml
@model Product


<div class="card shadow border-0 my-4">
	<div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Delete Product</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post">
			<input asp-for="Id" hidden />
			<div class="form-floating py-2 col-12">

				@* <div asp-validation-summary="All" class="text-danger"></div> *@
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="Title" disabled class="form-control border-0 shadow" class="ms-2" />
					<label asp-for="Title" class="ms-2"></label>
					<span asp-validation-for="Title" class="text-danger"></span>
				</div>
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="Description" disabled class="form-control border-0 shadow" />
					<label asp-for="Description" class="ms-2"></label>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="ISBN" disabled class="form-control border-0 shadow" />
					<label asp-for="ISBN" class="ms-2"></label>
					<span asp-validation-for="ISBN" class="text-danger"></span>
				</div>
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="Author" disabled class="form-control border-0 shadow" />
					<label asp-for="Author" class="ms-2"></label>
					<span asp-validation-for="Author" class="text-danger"></span>
				</div>
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="ListPrice" disabled class="form-control border-0 shadow" />
					<label asp-for="ListPrice" class="ms-2"></label>
					<span asp-validation-for="ListPrice" class="text-danger"></span>
				</div>
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="Price" disabled class="form-control border-0 shadow" />
					<label asp-for="Price" class="ms-2"></label>
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="Price50" disabled class="form-control border-0 shadow" />
					<label asp-for="Price50" class="ms-2"></label>
					<span asp-validation-for="Price50" class="text-danger"></span>
				</div>
				<div class=" form-floating mb-3 row p-1">
					<input asp-for="Price100" disabled class="form-control border-0 shadow" />
					<label asp-for="Price100" class="ms-2"></label>
					<span asp-validation-for="Price100" class="text-danger"></span>
				</div>

				<div class="row mt-3">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger form-control">Delete</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Product" asp-action="Index" class="btn btn-outline-primary form-control">
							Back to List
						</a>
					</div>
				</div>


			</div>
		</form>
	</div>
</div>



@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

MyWeb_MVC/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 my-4">
	<div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Company List</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">

			</div>
			<div class="col-6 text-end">
				<a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
					<i class="bi bi-plus-circle"></i> Create New Company
				</a>
			</div>
		</div>

		<table id="tblData" class="table table-bordered table-striped" style="width: 100%">
			<thead>
				<tr>
					<th>Name</th>
					<th>Address</th>
					<th>City</th>
					<th>State</th>
					<th>Phone Number</th>
					<th></th>
				</tr>
			</thead>
			
		</table>
	</div>
</div>

@section Scripts {
	<script src="~/js/company.js"></script>
}

MyWeb_MVC/Areas/Admin/Views/Company/Upsert.cshtml
@model Company
<div class="card shadow border-0 my-4">
	<div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">@(Model.Id!=0?"Update ":"Create ")Company</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<input asp-for="Id" hidden/>
			
			<div class="row">
				<div class="col-12">
					<div class="border p-3">

						@* <div asp-validation-summary="All" class="text-danger"></div> *@
						<div class=" form-floating mb-3 row p-1">
							<input asp-for="Name" class="form-control border-0 shadow" class="ms-2" />
							<label asp-for="Name" class="ms-2"></label>
							<span asp-validation-for="Name" class="text-danger"></span>
						</div>
						<div class=" form-floating mb-3 row p-1">
							<input asp-for="PhoneNumber" class="form-control border-0 shadow" />
							<label asp-for="PhoneNumber" class="ms-2"></label>
							<span asp-validation-for="PhoneNumber" class="text-danger"></span>
						</div>
						<div class=" form-floating mb-3 row p-1">
							<input asp-for="StreetAdress" class="form-control border-0 shadow" />
							<label asp-for="StreetAdress" class="ms-2"></label>
							<span asp-validation-for="StreetAdress" class="text-danger"></span>
						</div>
						<div class=" form-floating mb-3 row p-1">
							<input asp-for="City" class="form-control border-0 shadow" />
							<label asp-for="City" class="ms-2"></label>
							<span asp-validation-for="City" class="text-danger"></span>
						</div>
						<div class=" form-floating mb-3 row p-1">
							<input asp-for="State" class="form-control border-0 shadow" />
							<label asp-for="State" class="ms-2"></label>
							<span asp-validation-for="State" class="text-danger"></span>
						</div>
						<div class=" form-floating mb-3 row p-1">
							<input asp-for="PostalCode" class="form-control border-0 shadow" />
							<label asp-for="PostalCode" class="ms-2"></label>
							<span asp-validation-for="PostalCode" class="text-danger"></span>
						</div>
						

						<div class="row">
							<div class="col-6 col-md-3">
								@if (Model.Id != 0)
								{
									<button type="submit" class="btn btn-primary form-control">Update</button>
								}
								else
								{

									<button type="submit" class="btn btn-primary form-control">Create</button>
								}
							</div>
							<div class="col-6 col-md-3">
								<a asp-controller="Company" asp-action="Index" class="btn btn-outline-primary form-control">
									Back to List
								</a>
							</div>
						</div>


					</div>
				</div>
				
			</div>
			
		</form>
	</div>
</div>


@section Scripts{
	@{
		<script>
			tinymce.init({
			  selector: 'textarea',
			  plugins: [
				// Core editing features
				'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'image', 'link', 'lists', 'media', 'searchreplace', 'table', 'visualblocks', 'wordcount',
				// Your account includes a free trial of TinyMCE premium features
				// Try the most popular premium features until Apr 17, 2025:
				'checklist', 'mediaembed', 'casechange', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'editimage', 'advtemplate', 'ai', 'mentions', 'tinycomments', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown','importword', 'exportword', 'exportpdf'
			  ],
			  toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
			  tinycomments_mode: 'embedded',
			  tinycomments_author: 'Author name',
			  mergetags_list: [
				{ value: 'First.Name', title: 'First Name' },
				{ value: 'Email', title: 'Email' },
			  ],
			  ai_request: (request, respondWith) => respondWith.string(() => Promise.reject('See docs to implement AI Assistant')),
			});
		</script>
		<partial name="_ValidationScriptsPartial" />

	}
}